// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://parerglgduqtyiopkjlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcmVyZ2xnZHVxdHlpb3BramxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2Nzc5NDEsImV4cCI6MjA4NzI1Mzk0MX0.DquiTe0pil2RljyDAc0Y98gsmLTDP4lNlg3cbZhwPWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});