// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zigqblorggyzpsfhkqwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppZ3FibG9yZ2d5enBzZmhrcXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjA3NTEsImV4cCI6MjA2NzYzNjc1MX0.ma3aL2-tqlPGaNSnTZyJZNKpvJXImdZFE6SKOryLU4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});